
set(FILES
    Source/DioramaModuleInterface.cpp
    Source/DioramaModuleInterface.h
    Source/Clients/DioramaAssetUtils.h
    Source/Clients/DioramaSystemComponent.cpp
    Source/Clients/DioramaSystemComponent.h
    Source/Clients/SpriteComponent.cpp
    Source/Clients/SpriteComponent.h
    Source/Clients/SpriteComponentConfig.cpp
    Source/Clients/SpriteBus.cpp
    Source/Clients/SpriteRequestHandler.cpp
    Source/Clients/SpriteRequestHandler.h
    Source/Clients/SpriteAnimation.h
    Source/Clients/SpriteBatchPlan.h
    Source/Clients/Collision2D.h
    Source/Clients/Collision2DBus.cpp
    Source/Clients/Collision2DSystemComponent.cpp
    Source/Clients/Collision2DSystemComponent.h
    Source/Clients/Collider2DComponent.cpp
    Source/Clients/Collider2DComponent.h
    Source/Clients/Camera2D.h
    Source/Clients/Particles2D.h
    Source/Clients/SpriteFeatureProcessor.cpp
    Source/Clients/SpriteFeatureProcessor.h
    Source/Clients/SpritePresenter.cpp
    Source/Clients/SpritePresenter.h
    Source/Clients/DioramaLightComponent.cpp
    Source/Clients/DioramaLightComponent.h
    Source/Clients/LightPresenter.cpp
    Source/Clients/LightPresenter.h
    Source/Clients/TilemapComponent.cpp
    Source/Clients/TilemapComponent.h
    Source/Clients/TilemapComponentConfig.cpp
    Source/Clients/TilemapBus.cpp
    Source/Clients/TilemapRequestHandler.cpp
    Source/Clients/TilemapRequestHandler.h
    Source/Clients/TilemapPresenter.cpp
    Source/Clients/TilemapPresenter.h
)
